# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'iosStudying' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosStudying
  pod 'Alamofire', '~> 5.4.3'
  pod 'R.swift'
  pod 'KeychainSwift', '~> 19.0.0'

end
